=== s2quake/CremaRepository/.repository/databases/tables/Templates/ProjectInfo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:t="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo" xmlns="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo" elementFormDefault="qualified" targetNamespace="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo" version="4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="../../types/KindType.xsd" namespace="http://schemas.ntreev.com/crema/types/KindType" />
  <xs:import schemaLocation="../../types/ProjectType.xsd" namespace="http://schemas.ntreev.com/crema/types/ProjectType" />
  <xs:simpleType name="guid">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ProjectInfo.Table">
    <xs:annotation>
      <xs:appinfo>
        <TableInfo Modifier="admin" />
        <TableInfo ModifiedDateTime="2017-11-01T08:22:24.7493264Z" />
        <TableInfo ID="dea31cbb-0fbd-40b7-9e09-bf11038a3aca" />
        <TableInfo CategoryPath="/Templates/" />
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="KindType" xmlns:q1="http://schemas.ntreev.com/crema/types/KindType" type="q1:KindType">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T08:40:56.9613255Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-11-01T08:22:11.472703Z" />
            <ColumnInfo ID="53fd6271-0121-4f55-be26-7a47e64beebd" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ProjectType" xmlns:q2="http://schemas.ntreev.com/crema/types/ProjectType" type="q2:ProjectType">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-11-01T08:22:24.7337264Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-11-01T08:23:24.3338315Z" />
            <ColumnInfo ID="5c395fed-1fa0-4b1b-bca6-ac53fec0c950" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="Name" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T08:38:54.29831Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-25T08:42:24.92988Z" />
            <ColumnInfo ID="e8680af2-37c8-4719-bc81-6b2296952bc2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ProjectPath" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T08:25:15.4372718Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-25T08:42:25.6942813Z" />
            <ColumnInfo ID="fd83f5d6-3ae5-4889-8731-6228262ce181" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute default="" name="Creator" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="CreatedDateTime" type="xs:dateTime" />
    <xs:attribute default="" name="Modifier" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="ModifiedDateTime" type="xs:dateTime" />
    <xs:attribute default="All" name="Tags" type="xs:string" use="optional" />
    <xs:attribute default="true" name="Enable" type="xs:boolean" use="optional" />
    <xs:attribute name="RelationID" type="xs:string" />
  </xs:complexType>
  <xs:element name="Content">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="ProjectInfo" type="ProjectInfo.Table" />
      </xs:sequence>
      <xs:attribute name="Version" type="xs:string" use="required" />
      <xs:attribute name="ProjectInfo.CreatedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="ProjectInfo.Creator" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.ModifiedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="ProjectInfo.Modifier" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.Count" type="xs:int" use="optional" />
      <xs:attribute name="ProjectInfo.ID" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:key name="ProjectInfo.Key">
      <xs:selector xpath="t:ProjectInfo" />
      <xs:field xpath="t:KindType" />
      <xs:field xpath="t:Name" />
      <xs:field xpath="t:ProjectType" />
    </xs:key>
  </xs:element>
</xs:schema>

=== s2quake/CremaRepository/databases/8fe111c0-b9a3-4da1-86af-2ae07cea6a53/tables/Templates/ProjectInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="4.0"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo ProjectInfo.xsd"
  ProjectInfo.Modifier="s2quake"
  ProjectInfo.Count="6"
  ProjectInfo.ID="dea31cbb-0fbd-40b7-9e09-bf11038a3aca" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo">
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4202267Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3338315Z"
    RelationID="3690c9391151acd7057703cafb821469">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.SmartSet</Name>
    <ProjectPath>client/Ntreev.Crema.Client.SmartSet/Ntreev.Crema.Client.SmartSet.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4202267Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="e2d4fa01e336f756ad160c2cf7aa4711">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.Common</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Common/Ntreev.Crema.Client.Common.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4212452Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="e40206356bd63d3228d0c0facb669e62">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.Tables</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Tables/Ntreev.Crema.Client.Tables.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4212452Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="428ca329fea347e1a0505168bd8f4c63">
    <KindType>Common</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Presentation</Name>
    <ProjectPath>common/Ntreev.Crema.Presentation/Ntreev.Crema.Presentation.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4212452Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="0be414facb2c5e43ee76a909bfff3ae6">
    <KindType>SubModule</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.ModernUI.Framework</Name>
    <ProjectPath>sub-modules/Ntreev.ModernUI.Framework/Ntreev.ModernUI.Framework/Ntreev.ModernUI.Framework.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4212452Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T05:12:57.0171832Z"
    RelationID="f9b4fbf403945fc41e028283ad40d269">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.Converters</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Converters/Ntreev.Crema.Client.Converters.csproj</ProjectPath>
  </ProjectInfo>
</Content>

=== s2quake/CremaRepository/.repository/databases/tables/Export/CremaProjectInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="4.0"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/Export/CremaProjectInfo ../Templates/ProjectInfo.xsd"
  ProjectInfo.Modifier="s2quake"
  ProjectInfo.ModifiedDateTime="2018-04-05T00:28:45.3244102Z"
  ProjectInfo.Count="18"
  ProjectInfo.ID="dea31cbb-0fbd-40b7-9e09-bf11038a3aca" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo">
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4082187Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:33:26.5406935Z"
    RelationID="3690c9391151acd7057703cafb821469">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.SmartSet</Name>
    <ProjectPath>client/Ntreev.Crema.Client.SmartSet/Ntreev.Crema.Client.SmartSet.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4082187Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-28T05:09:10.5292629Z"
    RelationID="4dde656ba7408ba7c936cabb5e919d01">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.Base</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Base/Ntreev.Crema.Client.Base.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4082187Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="e40206356bd63d3228d0c0facb669e62">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.Tables</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Tables/Ntreev.Crema.Client.Tables.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4092194Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="428ca329fea347e1a0505168bd8f4c63">
    <KindType>Common</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Presentation</Name>
    <ProjectPath>common/Ntreev.Crema.Presentation/Ntreev.Crema.Presentation.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4092194Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="0be414facb2c5e43ee76a909bfff3ae6">
    <KindType>SubModule</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.ModernUI.Framework</Name>
    <ProjectPath>sub-modules/Ntreev.ModernUI.Framework/Ntreev.ModernUI.Framework/Ntreev.ModernUI.Framework.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4092194Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="f9b4fbf403945fc41e028283ad40d269">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.Converters</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Converters/Ntreev.Crema.Client.Converters.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4092194Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="0a934bc15cada78ddeb879533d760798">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.Types</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Types/Ntreev.Crema.Client.Types.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4092194Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="2734b8cfd24dbc1c4cbcc18d3fd402fb">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.Framework</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Framework/Ntreev.Crema.Client.Framework.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="admin"
    CreatedDateTime="2017-10-31T23:56:07.2660169Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="ef17faf8b3476143b61de6c27549dcaf">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.Console</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Console/Ntreev.Crema.Client.Console.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="admin"
    CreatedDateTime="2017-11-01T00:02:04.3818441Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:23:24.3494315Z"
    RelationID="37042365abfe9182b5e576b463c8e3be">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.Differences</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Differences/Ntreev.Crema.Client.Differences.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="admin"
    CreatedDateTime="2017-11-01T08:16:40.0885196Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T23:48:39.9346987Z"
    RelationID="56076ca6bf50315d854ae1652cd30339">
    <KindType>Client</KindType>
    <ProjectType>Executable</ProjectType>
    <Name>Ntreev.Crema.ApplicationHost</Name>
    <ProjectPath>client/Ntreev.Crema.ApplicationHost/Ntreev.Crema.ApplicationHost.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="admin"
    CreatedDateTime="2017-11-07T01:07:19.9852272Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T01:58:15.3087951Z"
    RelationID="f9a17874543a86ff807e1d24a07d60a1">
    <KindType>SubModule</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Library</Name>
    <ProjectPath>sub-modules/Ntreev.Library/Ntreev.Library/Ntreev.Library.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="admin"
    CreatedDateTime="2017-11-08T02:00:04.3097826Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-08T02:00:04.3097826Z"
    RelationID="0d919d314ac14af6ab4568f3b3475916">
    <KindType>Common</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.ServiceModel</Name>
    <ProjectPath>common/Ntreev.Crema.ServiceModel/Ntreev.Crema.ServiceModel.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="s2quake"
    CreatedDateTime="2017-11-08T08:04:13.6836813Z"
    Modifier="s2quake"
    ModifiedDateTime="2017-11-08T08:04:13.6836813Z"
    RelationID="b252ffe70db7149d155e3d747a6d6442">
    <KindType>Server</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.ServiceHosts</Name>
    <ProjectPath>server/Ntreev.Crema.ServiceHosts/Ntreev.Crema.ServiceHosts.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="s2quake"
    CreatedDateTime="2018-02-08T08:45:16.9001877Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-08T08:45:32.5002151Z"
    RelationID="c8f44f68760984fe73c2ceafeb501f64">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Client.Users</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Users/Ntreev.Crema.Client.Users.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="s2quake"
    CreatedDateTime="2018-02-27T00:04:02.7617631Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-27T00:04:02.7617631Z"
    RelationID="1f0059ca290c3679c52ad63a968d74fb">
    <KindType>Common</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Data</Name>
    <ProjectPath>common/Ntreev.Crema.Data/Ntreev.Crema.Data.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:08:35.6149548Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:08:35.6149548Z"
    RelationID="e608bc68-27dc-4af7-ba90-21bdbb8aaae3">
    <KindType>Client</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Services</Name>
    <ProjectPath>client/Ntreev.Crema.Services/Ntreev.Crema.Services.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="s2quake"
    CreatedDateTime="2018-04-05T00:28:45.3244102Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-04-05T00:28:45.3244102Z"
    RelationID="fc744d33-6996-4998-a016-36cef56ee4b4">
    <KindType>Server</KindType>
    <ProjectType>Library</ProjectType>
    <Name>Ntreev.Crema.Services</Name>
    <ProjectPath>server/Ntreev.Crema.Services/Ntreev.Crema.Services.csproj</ProjectPath>
  </ProjectInfo>
</Content>
