=== s2quake/CremaRepository/.repository/databases/tables/Templates/StringTable.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:t="http://schemas.ntreev.com/crema/tables/Templates/StringTable" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable" elementFormDefault="qualified" targetNamespace="http://schemas.ntreev.com/crema/tables/Templates/StringTable" version="4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="../../types/StringType.xsd" namespace="http://schemas.ntreev.com/crema/types/StringType" />
  <xs:simpleType name="guid">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="StringTable.Table">
    <xs:annotation>
      <xs:appinfo>
        <TableInfo Creator="admin" />
        <TableInfo CreatedDateTime="2017-10-23T07:16:01.2646706Z" />
        <TableInfo Modifier="admin" />
        <TableInfo ModifiedDateTime="2017-10-25T05:30:21.3826061Z" />
        <TableInfo ID="c0cab95d-e8db-454e-bfdd-db225b55d79e" />
        <TableInfo CategoryPath="/Templates/" />
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Type" xmlns:q1="http://schemas.ntreev.com/crema/types/StringType" type="q1:StringType">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:08.9674458Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:24.8392601Z" />
            <ColumnInfo ID="867a16ca-14f2-4d9f-9fd5-369db4fdb32c" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="Name" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:14.2230698Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:25.3766315Z" />
            <ColumnInfo ID="433aecf8-7727-434a-bc6f-39f39da28def" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Comment" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:18.3312332Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:18.3312332Z" />
            <ColumnInfo ID="ef0b7b57-02bd-4eb1-855d-56cde5678e3a" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Value" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:22.1143688Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:22.1143688Z" />
            <ColumnInfo ID="5d120517-873c-4042-a9af-ae13de2540af" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ko_KR" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T09:20:19.5441634Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T09:20:19.5441634Z" />
            <ColumnInfo ID="6d260fce-ea66-4244-98f3-2adb5c3fdaa4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute default="" name="Creator" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="CreatedDateTime" type="xs:dateTime" />
    <xs:attribute default="" name="Modifier" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="ModifiedDateTime" type="xs:dateTime" />
    <xs:attribute default="All" name="Tags" type="xs:string" use="optional" />
    <xs:attribute default="true" name="Enable" type="xs:boolean" use="optional" />
  </xs:complexType>
  <xs:element name="Content">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="StringTable" type="StringTable.Table" />
      </xs:sequence>
      <xs:attribute name="Version" type="xs:string" use="required" />
      <xs:attribute name="StringTable.CreatedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="StringTable.Creator" type="xs:string" use="optional" />
      <xs:attribute name="StringTable.ModifiedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="StringTable.Modifier" type="xs:string" use="optional" />
      <xs:attribute name="StringTable.Count" type="xs:int" use="optional" />
      <xs:attribute name="StringTable.ID" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:key name="StringTable.Key">
      <xs:selector xpath="t:StringTable" />
      <xs:field xpath="t:Type" />
      <xs:field xpath="t:Name" />
    </xs:key>
  </xs:element>
</xs:schema>

=== s2quake/CremaRepository/databases/8fe111c0-b9a3-4da1-86af-2ae07cea6a53/tables/client/ClientFramework.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="4.0"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/client/ClientFramework ../Templates/StringTable.xsd"
  StringTable.Creator="admin"
  StringTable.CreatedDateTime="2017-10-23T07:16:01.2646706Z"
  StringTable.Modifier="admin"
  StringTable.ModifiedDateTime="2018-04-06T07:39:01.7191079Z"
  StringTable.Count="32"
  StringTable.ID="c0cab95d-e8db-454e-bfdd-db225b55d79e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable">
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.371193Z"
    Modifier="admin"
    ModifiedDateTime="2018-04-06T07:38:59.0827033Z">
    <Type>Message</Type>
    <Name>ConfirmToResetSelectedFields</Name>
    <Comment>1</Comment>
    <Value>Do you want to reset selected fields?</Value>
    <ko_KR>선택된 필드의 값을 초기화 하시겠습니까?</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.371193Z"
    Modifier="admin"
    ModifiedDateTime="2018-04-06T07:39:01.7191079Z">
    <Type>Message</Type>
    <Name>ConfirmToDeleteSelectedRows_Format</Name>
    <Comment>2</Comment>
    <Value>Do you want to delete selected {0} rows?</Value>
    <ko_KR>택된 {0}개의 행을 삭제하시겠습니까?</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.371193Z"
    ModifiedDateTime="2017-10-31T06:53:14.371193Z">
    <Type>Message</Type>
    <Name>ConfirmToDeleteRow</Name>
    <Value>Do you want to delete row?</Value>
    <ko_KR>행을 삭제하시겠습니까?</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.371193Z"
    ModifiedDateTime="2017-10-31T06:53:14.371193Z">
    <Type>Message</Type>
    <Name>ConfirmToResetField</Name>
    <Value>Do you want to reset field?</Value>
    <ko_KR>필드의 값을 초기화하시겠습니까?</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.371193Z"
    ModifiedDateTime="2017-10-31T06:53:14.371193Z">
    <Type>Exception</Type>
    <Name>CannotSelectComplexRanges</Name>
    <Value>Selection of complex ranges is not possible.</Value>
    <ko_KR>복합적 범위의 선택은 불가능합니다.</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.371193Z"
    ModifiedDateTime="2017-10-31T06:53:14.371193Z">
    <Type>Exception</Type>
    <Name>ItsReadOnly_Format</Name>
    <Value>'{0}' is read only.</Value>
    <ko_KR>'{0}'은(는) 읽기 전용입니다.</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3721931Z"
    ModifiedDateTime="2017-10-31T06:53:14.3721931Z">
    <Type>Title</Type>
    <Name>SettingAuthority</Name>
    <Value>Setting Authority</Value>
    <ko_KR>권한 설정</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3721931Z"
    ModifiedDateTime="2017-10-31T06:53:14.3721931Z">
    <Type>Title</Type>
    <Name>SettingLock</Name>
    <Value>Setting Lock</Value>
    <ko_KR>잠금 설정</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3721931Z"
    ModifiedDateTime="2017-10-31T06:53:14.3721931Z">
    <Type>Message</Type>
    <Name>Locking</Name>
    <Value>Lock setting is in progress</Value>
    <ko_KR>잠금을 설정중입니다.</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3721931Z"
    ModifiedDateTime="2017-10-31T06:53:14.3721931Z">
    <Type>Label</Type>
    <Name>AccessView1</Name>
    <Value>User or group to invite</Value>
    <ko_KR>초대할 사용자 또는 그룹</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3721931Z"
    ModifiedDateTime="2017-10-31T06:53:14.3721931Z">
    <Type>Label</Type>
    <Name>AccessView2</Name>
    <Value>Users or Groups with Access Permissions</Value>
    <ko_KR>접근 권한이 있는 사용자 또는 그룹</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3721931Z"
    ModifiedDateTime="2017-10-31T06:53:14.3721931Z">
    <Type>Button</Type>
    <Name>Close</Name>
    <Value>_Close</Value>
    <ko_KR>닫기(_C)</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3721931Z"
    ModifiedDateTime="2017-10-31T06:53:14.3721931Z">
    <Type>Button</Type>
    <Name>Lock</Name>
    <Value>_Lock</Value>
    <ko_KR>잠금(_L)</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3721931Z"
    ModifiedDateTime="2017-10-31T06:53:14.3721931Z">
    <Type>Label</Type>
    <Name>Comment</Name>
    <Value>Comment</Value>
    <ko_KR>설명</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3721931Z"
    ModifiedDateTime="2017-10-31T06:53:14.3721931Z">
    <Type>Exception</Type>
    <Name>ColumnRangeExceeded</Name>
    <Value>The range of columns to paste has been exceeded.</Value>
    <ko_KR>붙여넣기 대상 열의 범위가 초과되었습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-08T00:03:47.8124104Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-08T00:03:47.8124104Z">
    <Type>MenuItem</Type>
    <Name>SetAuthority</Name>
    <Value>Set _Authority...</Value>
    <ko_KR>권한 설정(_A)...</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-08T00:03:47.8124104Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-08T00:03:47.8124104Z">
    <Type>MenuItem</Type>
    <Name>SetPrivate</Name>
    <Value>Set _Private</Value>
    <ko_KR>비공개로 설정(_P)</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-08T00:03:47.8124104Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-08T00:03:47.8124104Z">
    <Type>MenuItem</Type>
    <Name>SetPublic</Name>
    <Value>Set _Public</Value>
    <ko_KR>공개로 설정(_P)</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-08T00:03:47.8124104Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-08T00:03:47.8124104Z">
    <Type>MenuItem</Type>
    <Name>Unlock</Name>
    <Value>_Unlock</Value>
    <ko_KR>잠금 해제(_U)</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-08T00:03:47.8124104Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-08T00:03:47.8124104Z">
    <Type>MenuItem</Type>
    <Name>Lock</Name>
    <Value>_Lock...</Value>
    <ko_KR>잠금 설정(_L)...</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-08T00:03:47.8124104Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-08T00:03:47.8124104Z">
    <Type>MenuItem</Type>
    <Name>Load</Name>
    <Value>_Load...</Value>
    <ko_KR>활성화</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-08T00:03:47.8124104Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-08T00:03:47.8124104Z">
    <Type>MenuItem</Type>
    <Name>Unload</Name>
    <Value>_Unload...</Value>
    <ko_KR>비활성화</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-08T00:03:47.8124104Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-08T00:03:47.8124104Z">
    <Type>Message</Type>
    <Name>ConfirmToSetPrivate</Name>
    <Value>Do you want to set it to Private?</Value>
    <ko_KR>비공개로 설정하시겠습니까?</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-09T03:49:44.2246438Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-09T03:49:44.2246438Z">
    <Type>MenuItem</Type>
    <Name>Delete</Name>
    <Value>_Delete</Value>
    <ko_KR>삭제(_D)...</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-09T03:49:51.1354559Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-09T03:49:51.1354559Z">
    <Type>MenuItem</Type>
    <Name>Find</Name>
    <Value>_Find</Value>
    <ko_KR>찾기(_F)</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-09T03:49:55.4566635Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-09T04:04:17.7873786Z">
    <Type>MenuItem</Type>
    <Name>Move</Name>
    <Value>_Move...</Value>
    <ko_KR>이동(_M)...</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-09T03:50:00.4642723Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-09T04:04:19.4877816Z">
    <Type>MenuItem</Type>
    <Name>Rename</Name>
    <Value>_Rename...</Value>
    <ko_KR>이름 변경(_R)...</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-09T04:03:12.6416641Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-20T06:15:31.0859959Z">
    <Type>MenuItem</Type>
    <Name>Copy</Name>
    <Value>_Copy...</Value>
    <ko_KR>복사(_C)...</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-19T07:52:23.0537689Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-19T07:52:23.0537689Z">
    <Type>MenuItem</Type>
    <Name>NewFolder</Name>
    <Value>_New Folder</Value>
    <ko_KR>새 폴더(_N)...</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-02-27T06:55:46.2411428Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-27T06:55:46.2411428Z">
    <Type>MenuItem</Type>
    <Name>ViewLog</Name>
    <Value>View Log</Value>
    <ko_KR>로그 보기(_L)...</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-07T05:39:34.1834436Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-07T05:39:34.1834436Z">
    <Type>MenuItem</Type>
    <Name>CancelEdit</Name>
    <Value>Cancel Edit</Value>
    <ko_KR>편집 취소</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-07T05:39:34.1834436Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-07T05:39:34.1834436Z">
    <Type>MenuItem</Type>
    <Name>EndEdit</Name>
    <Value>End Edit</Value>
    <ko_KR>편집 종료</ko_KR>
  </StringTable>
</Content>

=== s2quake/CremaRepository/databases/8fe111c0-b9a3-4da1-86af-2ae07cea6a53/tables/sub-modules/NtreevLibrary.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="4.0"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/sub-modules/NtreevLibrary ../Templates/StringTable.xsd"
  StringTable.Creator="admin"
  StringTable.CreatedDateTime="2017-10-23T07:16:01.2646706Z"
  StringTable.ModifiedDateTime="2018-01-26T05:04:28.2807632Z"
  StringTable.Count="25"
  StringTable.ID="c0cab95d-e8db-454e-bfdd-db225b55d79e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable">
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-06T23:48:25.3943089Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:20:09.894855Z">
    <Type>Exception</Type>
    <Name>AlreadyRegisteredProperty_Format</Name>
    <Value>Property '{0}' is already registered.</Value>
    <ko_KR>'{0}' 속성은 이미 등록되어 있습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-06T23:49:46.6412517Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:20:03.3584435Z">
    <Type>Exception</Type>
    <Name>NotFoundProperty_Format</Name>
    <Value>Property '{0}' does not exist.</Value>
    <ko_KR>'{0}' 속성은 존재하지 않습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-06T23:52:46.9795686Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:19:51.720823Z">
    <Type>Exception</Type>
    <Name>InvalidPropertyType_Format</Name>
    <Value>Type '{0}' can not be used as property.</Value>
    <ko_KR>'{0}' 속성은 사용할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-06T23:54:05.9157072Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:19:37.2283976Z">
    <Type>Exception</Type>
    <Name>UndefinedValue_Format</Name>
    <Value>Value '{0}' is not defined.</Value>
    <ko_KR>'{0}' 값은 정의되어 있지 않습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-06T23:58:06.5325299Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-06T23:58:37.827185Z">
    <Type>Exception</Type>
    <Name>NotFoundDirectory_Format</Name>
    <Value>Path '{0}' could not be found.</Value>
    <ko_KR>'{0}' 경로를 찾을 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-06T23:59:10.4312422Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-06T23:59:19.9160589Z">
    <Type>Exception</Type>
    <Name>NotIncludedParentPath</Name>
    <Value>The path to the file does not include the parent path.</Value>
    <ko_KR>파일 경로에 부모 경로가 포함되어 있지 않습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T00:00:05.5939392Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:00:15.5467566Z">
    <Type>Exception</Type>
    <Name>InvalidPath</Name>
    <Value>Invalid path.</Value>
    <ko_KR>잘못된 경로입니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T00:21:58.1756452Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:22:50.8891378Z">
    <Type>Exception</Type>
    <Name>InvalidPath_Format</Name>
    <Value>'{0}' is invalid path.</Value>
    <ko_KR>'{0}' 은(는) 잘못된 경로입니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T00:01:17.8532661Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T01:59:03.60648Z">
    <Type>Exception</Type>
    <Name>CyclicDependency</Name>
    <Value>Cyclic dependency found.</Value>
    <ko_KR>주기적 종속성을 발견했습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T00:18:11.1152463Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:19:25.512777Z">
    <Type>Exception</Type>
    <Name>NotSupportedType_Format</Name>
    <Value>Type '{0} is not supported.</Value>
    <ko_KR>'{0}' 타입은 지원되지 않습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T00:20:59.1295415Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:21:14.3083682Z">
    <Type>Exception</Type>
    <Name>Between0and1</Name>
    <Value>Values between 0 and 1 must be used.</Value>
    <ko_KR>0 과 1사이의 값을 사용해야 합니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T00:24:26.5339059Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T02:03:52.5989877Z">
    <Type>Exception</Type>
    <Name>InvalidName</Name>
    <Value>Name can not include special characters \ / : * ? &lt; &gt; | etc.</Value>
    <ko_KR>이름에 특수문자 \ / : * ? " &lt; &gt; | 등은 포함될 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T00:25:24.8156083Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-01-11T06:29:07.6857211Z">
    <Type>Exception</Type>
    <Name>AlreadyExistedItem_Format</Name>
    <Value>Item '{0}' is already existed.</Value>
    <ko_KR>'{0}' 항목은 이미 존재합니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T00:26:59.3995744Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:27:13.392799Z">
    <Type>Exception</Type>
    <Name>SameItemInParent</Name>
    <Value>Item with same name exists in parent folder.</Value>
    <ko_KR>부모 폴더에 이름이 같은 항목이 존재합니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T00:27:44.0780529Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:27:56.651675Z">
    <Type>Exception</Type>
    <Name>SameFolderInParent</Name>
    <Value>Folder with same name exists in parent folder.</Value>
    <ko_KR>부모 폴더에 이름이 같은 폴더가 존재합니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T00:28:15.5755083Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:30:25.165936Z">
    <Type>Exception</Type>
    <Name>NotFoundFolder_Format</Name>
    <Value>Folder '{0}' could not be found.</Value>
    <ko_KR>'{0}' 폴더를 찾을 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T00:47:00.5814848Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T00:47:18.2719159Z">
    <Type>Exception</Type>
    <Name>IndestructibleObject</Name>
    <Value>Indestructible Object</Value>
    <ko_KR>삭제할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T02:00:22.1068179Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T02:00:25.6480241Z">
    <Type>Message</Type>
    <Name>Completed</Name>
    <Value>Completed.</Value>
    <ko_KR>완료되었습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T02:04:45.3582803Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T02:05:08.8363216Z">
    <Type>Exception</Type>
    <Name>EmptyStringCannotBeUsedAsName</Name>
    <Value>Empty string can not be used as a name.</Value>
    <ko_KR>빈 문자열을 이름으로 사용할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T02:07:41.4367897Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T02:08:00.7662237Z">
    <Type>Exception</Type>
    <Name>NotFoundItem_Format</Name>
    <Value>Item '{0}' could not be found.</Value>
    <ko_KR>'{0}' 항목을 찾을 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T02:09:32.1989843Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T02:10:04.5690412Z">
    <Type>Exception</Type>
    <Name>UniqueObjectCannotRename</Name>
    <Value>You can not rename objects whose unique name property is set.</Value>
    <ko_KR>고유 이름 속성이 설정된 객체는 이름을 변경할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T02:10:45.8155136Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T02:11:10.0579562Z">
    <Type>Exception</Type>
    <Name>InvalidName_Format</Name>
    <Value>'{0}' is invalid name</Value>
    <ko_KR>'{0}' 은(는) 잘못된 이름입니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T02:15:32.313017Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T02:15:40.7214318Z">
    <Type>Exception</Type>
    <Name>ChildFolderCannotBeSetAsParent</Name>
    <Value>Child folders in folders can not be set as parents.</Value>
    <ko_KR>폴더의 하위 폴더는 부모로 설정할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T02:16:27.9427147Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T02:19:26.5494285Z">
    <Type>Exception</Type>
    <Name>UnnamedFolderCannotHaveParent</Name>
    <Value>A folder without a name can not be set up by a parent folder.</Value>
    <ko_KR>이름이 없는 폴더는 부모 폴더를 설정할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-07T02:20:42.4903619Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-07T02:21:17.0610227Z">
    <Type>Exception</Type>
    <Name>CannotBeSetItSelfAsParent</Name>
    <Value>Unable to set self to parent folder.</Value>
    <ko_KR>자기 자신을 부모 폴더로 설정할 수 없습니다.</ko_KR>
  </StringTable>
</Content>

=== s2quake/CremaRepository/.repository/databases/tables/client/ClientConsole.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="4.0"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/client/ClientConsole ../Templates/StringTable.xsd"
  StringTable.Creator="admin"
  StringTable.CreatedDateTime="2017-10-23T07:16:01.2646706Z"
  StringTable.Modifier="s2quake"
  StringTable.ModifiedDateTime="2018-02-22T06:11:33.5626189Z"
  StringTable.Count="5"
  StringTable.ID="96eb902b-050d-4aa6-bf63-15881775de57" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable">
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-10-31T23:48:31.1368157Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-02-22T06:11:33.5626189Z">
    <Type>Title</Type>
    <Name>Console</Name>
    <Value>Console</Value>
    <ko_KR>콘솔</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-10-31T23:50:01.6949748Z"
    Modifier="admin"
    ModifiedDateTime="2017-10-31T23:52:40.2068532Z">
    <Type>Comment</Type>
    <Name>Hello</Name>
    <Value>Hello!</Value>
    <ko_KR>안녕하세요 !</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-10-31T23:50:12.5213938Z"
    Modifier="admin"
    ModifiedDateTime="2017-10-31T23:52:44.9960616Z">
    <Type>Comment</Type>
    <Name>AvaliableCommands</Name>
    <Value>Avaliable Commands:</Value>
    <ko_KR>사용 가능한 명령들:</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-10-31T23:50:28.9950227Z"
    Modifier="admin"
    ModifiedDateTime="2017-10-31T23:52:54.6056785Z">
    <Type>Comment</Type>
    <Name>TypeHelp</Name>
    <Value>type 'help' for usage.</Value>
    <ko_KR>도움말을 사용하시려면 'help'을(를) 입력하세요.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-10-31T23:50:41.662245Z"
    Modifier="admin"
    ModifiedDateTime="2017-10-31T23:52:56.1500812Z">
    <Type>Comment</Type>
    <Name>TypeVersion</Name>
    <Value>type '--version' to see the version.</Value>
    <ko_KR>버전을 확인하시려면 '--version'을(를) 입력하세요.</ko_KR>
  </StringTable>
</Content>
