=== s2quake/CremaRepository/.repository/databases/tables/Templates/StringTable.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:t="http://schemas.ntreev.com/crema/tables/Templates/StringTable" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable" elementFormDefault="qualified" targetNamespace="http://schemas.ntreev.com/crema/tables/Templates/StringTable" version="4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="../../types/StringType.xsd" namespace="http://schemas.ntreev.com/crema/types/StringType" />
  <xs:simpleType name="guid">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="StringTable.Table">
    <xs:annotation>
      <xs:appinfo>
        <TableInfo Creator="admin" />
        <TableInfo CreatedDateTime="2017-10-23T07:16:01.2646706Z" />
        <TableInfo Modifier="admin" />
        <TableInfo ModifiedDateTime="2017-10-25T05:30:21.3826061Z" />
        <TableInfo ID="c0cab95d-e8db-454e-bfdd-db225b55d79e" />
        <TableInfo CategoryPath="/Templates/" />
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Type" xmlns:q1="http://schemas.ntreev.com/crema/types/StringType" type="q1:StringType">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:08.9674458Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:24.8392601Z" />
            <ColumnInfo ID="867a16ca-14f2-4d9f-9fd5-369db4fdb32c" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="Name" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:14.2230698Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:25.3766315Z" />
            <ColumnInfo ID="433aecf8-7727-434a-bc6f-39f39da28def" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Comment" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:18.3312332Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:18.3312332Z" />
            <ColumnInfo ID="ef0b7b57-02bd-4eb1-855d-56cde5678e3a" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Value" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:22.1143688Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:22.1143688Z" />
            <ColumnInfo ID="5d120517-873c-4042-a9af-ae13de2540af" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ko_KR" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T09:20:19.5441634Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T09:20:19.5441634Z" />
            <ColumnInfo ID="6d260fce-ea66-4244-98f3-2adb5c3fdaa4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute default="" name="Creator" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="CreatedDateTime" type="xs:dateTime" />
    <xs:attribute default="" name="Modifier" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="ModifiedDateTime" type="xs:dateTime" />
    <xs:attribute default="All" name="Tags" type="xs:string" use="optional" />
    <xs:attribute default="true" name="Enable" type="xs:boolean" use="optional" />
  </xs:complexType>
  <xs:element name="Content">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="StringTable" type="StringTable.Table" />
      </xs:sequence>
      <xs:attribute name="Version" type="xs:string" use="required" />
      <xs:attribute name="StringTable.CreatedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="StringTable.Creator" type="xs:string" use="optional" />
      <xs:attribute name="StringTable.ModifiedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="StringTable.Modifier" type="xs:string" use="optional" />
      <xs:attribute name="StringTable.Count" type="xs:int" use="optional" />
      <xs:attribute name="StringTable.ID" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:key name="StringTable.Key">
      <xs:selector xpath="t:StringTable" />
      <xs:field xpath="t:Type" />
      <xs:field xpath="t:Name" />
    </xs:key>
  </xs:element>
</xs:schema>

=== s2quake/CremaRepository/databases/8fe111c0-b9a3-4da1-86af-2ae07cea6a53/tables/common/CommonPresentation.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="4.0"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/common/CommonPresentation ../Templates/StringTable.xsd"
  StringTable.Creator="admin"
  StringTable.CreatedDateTime="2017-10-23T07:16:01.2646706Z"
  StringTable.ModifiedDateTime="2017-10-31T06:53:14.405216Z"
  StringTable.Count="26"
  StringTable.ID="c0cab95d-e8db-454e-bfdd-db225b55d79e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable">
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4032155Z"
    ModifiedDateTime="2017-10-31T06:53:14.4032155Z">
    <Type>Command</Type>
    <Name>AddItemToLeftSide</Name>
    <Value>Add item to left side</Value>
    <ko_KR>좌측에 행 추가</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4032155Z"
    ModifiedDateTime="2017-10-31T06:53:14.4032155Z">
    <Type>Command</Type>
    <Name>AddItemToRightSide</Name>
    <Value>Add item to right side</Value>
    <ko_KR>우측에 행 추가</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4032155Z"
    ModifiedDateTime="2017-10-31T06:53:14.4032155Z">
    <Type>Command</Type>
    <Name>CopyFieldToLeftSide</Name>
    <Value>Copy field to left side</Value>
    <ko_KR>좌측에 값 복사</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4032155Z"
    ModifiedDateTime="2017-10-31T06:53:14.4032155Z">
    <Type>Command</Type>
    <Name>CopyFieldToRightSide</Name>
    <Value>Copy field to right side</Value>
    <ko_KR>우측에 값 복사</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4032155Z"
    ModifiedDateTime="2017-10-31T06:53:14.4032155Z">
    <Type>Command</Type>
    <Name>CopyItemToLeftSide</Name>
    <Value>Copy item to left side</Value>
    <ko_KR>좌측에 행 복사</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4032155Z"
    ModifiedDateTime="2017-10-31T06:53:14.4032155Z">
    <Type>Command</Type>
    <Name>CopyItemToRightSide</Name>
    <Value>Copy item to right side</Value>
    <ko_KR>우측에 행 복사</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4032155Z"
    ModifiedDateTime="2017-10-31T06:53:14.4032155Z">
    <Type>Command</Type>
    <Name>Delete</Name>
    <Value>Delete</Value>
    <ko_KR>삭제(_D)</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4032155Z"
    ModifiedDateTime="2017-10-31T06:53:14.4032155Z">
    <Type>Command</Type>
    <Name>Merge</Name>
    <Value>Merge</Value>
    <ko_KR>병합</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4042159Z"
    ModifiedDateTime="2017-10-31T06:53:14.4042159Z">
    <Type>Command</Type>
    <Name>NextDifferenceField</Name>
    <Value>Next difference field</Value>
    <ko_KR>다른 다음 값으로</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4042159Z"
    ModifiedDateTime="2017-10-31T06:53:14.4042159Z">
    <Type>Command</Type>
    <Name>NextDifferenceItem</Name>
    <Value>Next difference item</Value>
    <ko_KR>다른 다음 항목으로</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4042159Z"
    ModifiedDateTime="2017-10-31T06:53:14.4042159Z">
    <Type>Command</Type>
    <Name>PrevDifferenceField</Name>
    <Value>Previous difference field</Value>
    <ko_KR>다른 이전 값으로</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4042159Z"
    ModifiedDateTime="2017-10-31T06:53:14.4042159Z">
    <Type>Command</Type>
    <Name>PrevDifferenceItem</Name>
    <Value>Previous difference item</Value>
    <ko_KR>다른 이전 항목으로</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4042159Z"
    ModifiedDateTime="2017-10-31T06:53:14.4042159Z">
    <Type>Command</Type>
    <Name>Resolve</Name>
    <Value>Resolve</Value>
    <ko_KR>해결됨으로 표시</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4042159Z"
    ModifiedDateTime="2017-10-31T06:53:14.4042159Z">
    <Type>Label</Type>
    <Name>Comment</Name>
    <Value>Comment</Value>
    <ko_KR>설명</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4042159Z"
    ModifiedDateTime="2017-10-31T06:53:14.4042159Z">
    <Type>Label</Type>
    <Name>CreatedDateTime</Name>
    <Value>Created DateTime</Value>
    <ko_KR>생성 일자</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4042159Z"
    ModifiedDateTime="2017-10-31T06:53:14.4042159Z">
    <Type>Label</Type>
    <Name>CreationInfo</Name>
    <Value>Creation Info</Value>
    <ko_KR>생성 정보</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.4042159Z"
    ModifiedDateTime="2017-10-31T06:53:14.4042159Z">
    <Type>Label</Type>
    <Name>Creator</Name>
    <Value>Creator</Value>
    <ko_KR>생성한 사람</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.405216Z"
    ModifiedDateTime="2017-10-31T06:53:14.405216Z">
    <Type>Label</Type>
    <Name>IsFlag</Name>
    <Value>IsFlag</Value>
    <ko_KR>플래그 집합</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.405216Z"
    ModifiedDateTime="2017-10-31T06:53:14.405216Z">
    <Type>Label</Type>
    <Name>ModificationInfo</Name>
    <Value>Modification Info</Value>
    <ko_KR>변경 정보</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.405216Z"
    ModifiedDateTime="2017-10-31T06:53:14.405216Z">
    <Type>Label</Type>
    <Name>ModifiedDateTime</Name>
    <Value>Modified DateTime</Value>
    <ko_KR>변경 일자</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.405216Z"
    ModifiedDateTime="2017-10-31T06:53:14.405216Z">
    <Type>Label</Type>
    <Name>Modifier</Name>
    <Value>Modifier</Value>
    <ko_KR>변경한 사람</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.405216Z"
    ModifiedDateTime="2017-10-31T06:53:14.405216Z">
    <Type>Label</Type>
    <Name>Name</Name>
    <Value>Name</Value>
    <ko_KR>이름</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.405216Z"
    ModifiedDateTime="2017-10-31T06:53:14.405216Z">
    <Type>Label</Type>
    <Name>TableName</Name>
    <Value>Table Name</Value>
    <ko_KR>테이블 이름</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.405216Z"
    ModifiedDateTime="2017-10-31T06:53:14.405216Z">
    <Type>Label</Type>
    <Name>Tags</Name>
    <Value>Tags</Value>
    <ko_KR>태그</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.405216Z"
    ModifiedDateTime="2017-10-31T06:53:14.405216Z">
    <Type>Label</Type>
    <Name>TypeName</Name>
    <Value>Type Name</Value>
    <ko_KR>타입 이름</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.405216Z"
    ModifiedDateTime="2017-10-31T06:53:14.405216Z">
    <Type>Label</Type>
    <Name>Value</Name>
    <Value>Value</Value>
    <ko_KR>값</ko_KR>
  </StringTable>
</Content>

=== s2quake/CremaRepository/.repository/databases/tables/server/ServerServiceHosts.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="4.0"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/server/ServerServiceHosts ../Templates/StringTable.xsd"
  StringTable.Creator="admin"
  StringTable.CreatedDateTime="2017-10-23T07:16:01.2646706Z"
  StringTable.Modifier="s2quake"
  StringTable.ModifiedDateTime="2017-11-08T08:00:43.9046827Z"
  StringTable.Count="4"
  StringTable.ID="36ac8b33-93d6-4d96-a026-668e8ff22b73" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable">
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2017-11-08T07:59:19.8868771Z"
    Modifier="s2quake"
    ModifiedDateTime="2017-11-08T07:59:19.8868771Z">
    <Type>None</Type>
    <Name>ServiceStart</Name>
    <Value>{0} service has been started.</Value>
    <ko_KR>{0} 서비스가 시작되었습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2017-11-08T07:59:19.8868771Z"
    Modifier="s2quake"
    ModifiedDateTime="2017-11-08T07:59:19.8868771Z">
    <Type>None</Type>
    <Name>ServiceStart_Port</Name>
    <Value>{0}({1}) service has been started.</Value>
    <ko_KR>{0}({1}) 서비스가 시작되었습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2017-11-08T07:59:19.8868771Z"
    Modifier="s2quake"
    ModifiedDateTime="2017-11-08T07:59:19.8868771Z">
    <Type>None</Type>
    <Name>ServiceStop</Name>
    <Value>{0} service has been stopped.</Value>
    <ko_KR>{0} 서비스가 종료되었습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2017-11-08T08:00:20.3643362Z"
    Modifier="s2quake"
    ModifiedDateTime="2017-11-08T08:00:43.9046827Z">
    <Type>Exception</Type>
    <Name>LowerVersion</Name>
    <Value>Version is lower than the server.</Value>
    <ko_KR>버전이 서버보다 낮습니다.</ko_KR>
  </StringTable>
</Content>

=== s2quake/CremaRepository/databases/8fe111c0-b9a3-4da1-86af-2ae07cea6a53/tables/client/ClientDifferences.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="4.0"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/client/ClientDifferences ../Templates/StringTable.xsd"
  StringTable.Creator="admin"
  StringTable.CreatedDateTime="2017-10-23T07:16:01.2646706Z"
  StringTable.Modifier="admin"
  StringTable.ModifiedDateTime="2017-11-01T07:58:20.3605835Z"
  StringTable.Count="23"
  StringTable.ID="867b99c7-414f-4ca7-90a1-8c5ac83b0518" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable">
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T00:01:28.6733814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:33:45.7471067Z">
    <Type>Title</Type>
    <Name>Differences</Name>
    <Value>Differences</Value>
    <ko_KR>비교</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:30:21.5739481Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:30:39.2487792Z">
    <Type>Button</Type>
    <Name>Merge</Name>
    <Value>_Merge</Value>
    <ko_KR>병합(_M)</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:30:26.9091575Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:30:42.2751845Z">
    <Type>Button</Type>
    <Name>OK</Name>
    <Value>_OK</Value>
    <ko_KR>확인(_O)</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>Comment</Name>
    <Value>Comment</Value>
    <ko_KR>설명</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>ContentModifiedDateTime</Name>
    <Value>Content Modified DateTime</Value>
    <ko_KR>데이터 변경 일자</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>ContentModifier</Name>
    <Value>Content Modifier</Value>
    <ko_KR>데이터 변경자</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>CreatedDateTime</Name>
    <Value>Created DateTime</Value>
    <ko_KR>생성 일자</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>Creator</Name>
    <Value>Creator</Value>
    <ko_KR>생성자</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>IsFlag</Name>
    <Value>Is Flag</Value>
    <ko_KR>플래그 집합</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>ModifiedDateTime</Name>
    <Value>Modified DateTime</Value>
    <ko_KR>변경자</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>Modifier</Name>
    <Value>Modifier</Value>
    <ko_KR>변경 일자</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>Name</Name>
    <Value>Name</Value>
    <ko_KR>이름</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>Path</Name>
    <Value>Path</Value>
    <ko_KR>경로</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>TableName</Name>
    <Value>Table Name</Value>
    <ko_KR>테이블 이름</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>Tags</Name>
    <Value>Tags</Value>
    <ko_KR>태그</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>TemplatedParent</Name>
    <Value>Templated Parent</Value>
    <ko_KR>부모 템플릿</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>TemplateModifiedDateTime</Name>
    <Value>Template Modified DateTime</Value>
    <ko_KR>형태 변경 일자</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:23.3945621Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:32:23.3945621Z">
    <Type>Label</Type>
    <Name>TemplateModifier</Name>
    <Value>Template Modifier</Value>
    <ko_KR>형태 변경자</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:33:07.9950404Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:34:21.8455701Z">
    <Type>Title</Type>
    <Name>ColumnInfo</Name>
    <Value>Column Information</Value>
    <ko_KR>컬럼 정보</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:33:20.6466627Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:34:19.1779655Z">
    <Type>Title</Type>
    <Name>TableInfo</Name>
    <Value>Table Information</Value>
    <ko_KR>테이블 정보</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:33:26.3250726Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T01:34:16.3699605Z">
    <Type>Title</Type>
    <Name>TypeInfo</Name>
    <Value>Type Information</Value>
    <ko_KR>타입 정보</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T01:32:42.145795Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T07:51:52.0132988Z">
    <Type>MenuItem</Type>
    <Name>CompareWithPreviousResivision</Name>
    <Value>Compare With Previous Resivision...</Value>
    <ko_KR>이전 리비전과 비교하기...</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-01T07:51:24.1954498Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T07:58:20.3605835Z">
    <Type>MenuItem</Type>
    <Name>CompareWithLatestRevision</Name>
    <Value>Compare With Latest Revision...</Value>
    <ko_KR>최근 리비전과 비교하기...</ko_KR>
  </StringTable>
</Content>
