=== s2quake/CremaRepository/.repository/databases/tables/Templates/StringTable.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:t="http://schemas.ntreev.com/crema/tables/Templates/StringTable" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable" elementFormDefault="qualified" targetNamespace="http://schemas.ntreev.com/crema/tables/Templates/StringTable" version="4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="../../types/StringType.xsd" namespace="http://schemas.ntreev.com/crema/types/StringType" />
  <xs:simpleType name="guid">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="StringTable.Table">
    <xs:annotation>
      <xs:appinfo>
        <TableInfo Creator="admin" />
        <TableInfo CreatedDateTime="2017-10-23T07:16:01.2646706Z" />
        <TableInfo Modifier="admin" />
        <TableInfo ModifiedDateTime="2017-10-25T05:30:21.3826061Z" />
        <TableInfo ID="c0cab95d-e8db-454e-bfdd-db225b55d79e" />
        <TableInfo CategoryPath="/Templates/" />
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Type" xmlns:q1="http://schemas.ntreev.com/crema/types/StringType" type="q1:StringType">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:08.9674458Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:24.8392601Z" />
            <ColumnInfo ID="867a16ca-14f2-4d9f-9fd5-369db4fdb32c" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="Name" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:14.2230698Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:25.3766315Z" />
            <ColumnInfo ID="433aecf8-7727-434a-bc6f-39f39da28def" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Comment" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:18.3312332Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:18.3312332Z" />
            <ColumnInfo ID="ef0b7b57-02bd-4eb1-855d-56cde5678e3a" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Value" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T07:16:22.1143688Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T07:16:22.1143688Z" />
            <ColumnInfo ID="5d120517-873c-4042-a9af-ae13de2540af" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ko_KR" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-23T09:20:19.5441634Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-23T09:20:19.5441634Z" />
            <ColumnInfo ID="6d260fce-ea66-4244-98f3-2adb5c3fdaa4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute default="" name="Creator" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="CreatedDateTime" type="xs:dateTime" />
    <xs:attribute default="" name="Modifier" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="ModifiedDateTime" type="xs:dateTime" />
    <xs:attribute default="All" name="Tags" type="xs:string" use="optional" />
    <xs:attribute default="true" name="Enable" type="xs:boolean" use="optional" />
  </xs:complexType>
  <xs:element name="Content">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="StringTable" type="StringTable.Table" />
      </xs:sequence>
      <xs:attribute name="Version" type="xs:string" use="required" />
      <xs:attribute name="StringTable.CreatedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="StringTable.Creator" type="xs:string" use="optional" />
      <xs:attribute name="StringTable.ModifiedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="StringTable.Modifier" type="xs:string" use="optional" />
      <xs:attribute name="StringTable.Count" type="xs:int" use="optional" />
      <xs:attribute name="StringTable.ID" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:key name="StringTable.Key">
      <xs:selector xpath="t:StringTable" />
      <xs:field xpath="t:Type" />
      <xs:field xpath="t:Name" />
    </xs:key>
  </xs:element>
</xs:schema>

=== s2quake/CremaRepository/.repository/databases/tables/client/ClientConverters.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="4.0"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/client/ClientConverters ../Templates/StringTable.xsd"
  StringTable.Creator="admin"
  StringTable.CreatedDateTime="2017-10-23T07:16:01.2646706Z"
  StringTable.ModifiedDateTime="2018-01-26T05:04:28.2822641Z"
  StringTable.Count="30"
  StringTable.ID="c0cab95d-e8db-454e-bfdd-db225b55d79e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable">
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.368191Z"
    ModifiedDateTime="2017-10-31T06:53:14.368191Z">
    <Type>Title</Type>
    <Name>Export</Name>
    <Value>Export</Value>
    <ko_KR>내보내기</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.368191Z"
    ModifiedDateTime="2017-10-31T06:53:14.368191Z">
    <Type>Title</Type>
    <Name>Import</Name>
    <Value>Import</Value>
    <ko_KR>가져오기</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.368191Z"
    ModifiedDateTime="2017-10-31T06:53:14.368191Z">
    <Type>Message</Type>
    <Name>ReceivingData</Name>
    <Value>Receiving Data.</Value>
    <ko_KR>데이터를 가져오고 있습니다.</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.368191Z"
    ModifiedDateTime="2017-10-31T06:53:14.368191Z">
    <Type>Message</Type>
    <Name>ExportingData</Name>
    <Value>Exporting Data.</Value>
    <ko_KR>데이터를 내보내고 있습니다.</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.368191Z"
    ModifiedDateTime="2017-10-31T06:53:14.368191Z">
    <Type>Message</Type>
    <Name>ReceivingDataFormat</Name>
    <Value>Receiving Data : {0}</Value>
    <ko_KR>데이터를 가져오고 있습니다. : {0}</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3691911Z"
    ModifiedDateTime="2017-10-31T06:53:14.3691911Z">
    <Type>Message</Type>
    <Name>ExportingDataFormat</Name>
    <Value>Exporting Data : {0}</Value>
    <ko_KR>데이터를 내보내고 있습니다. : {0}</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3691911Z"
    ModifiedDateTime="2017-10-31T06:53:14.3691911Z">
    <Type>Message</Type>
    <Name>Exported</Name>
    <Value>Exported.</Value>
    <ko_KR>내보내기를 완료했습니다.</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3691911Z"
    ModifiedDateTime="2017-10-31T06:53:14.3691911Z">
    <Type>Message</Type>
    <Name>Canceling</Name>
    <Value>Canceling.</Value>
    <ko_KR>취소하는 중입니다.</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3691911Z"
    ModifiedDateTime="2017-10-31T06:53:14.3691911Z">
    <Type>Message</Type>
    <Name>Importing</Name>
    <Value>Importing.</Value>
    <ko_KR>가져오는 중입니다.</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3691911Z"
    ModifiedDateTime="2017-10-31T06:53:14.3691911Z">
    <Type>Message</Type>
    <Name>Imported</Name>
    <Value>Imported.</Value>
    <ko_KR>가져오기를 완료했습니다.</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3691911Z"
    ModifiedDateTime="2017-10-31T06:53:14.3691911Z">
    <Type>Message</Type>
    <Name>NoneTablesToExport</Name>
    <Value>No tables can be exported.</Value>
    <ko_KR>내보낼 수 있는 테이블이 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3691911Z"
    ModifiedDateTime="2017-10-31T06:53:14.3691911Z">
    <Type>Label</Type>
    <Name>ExportingInformation</Name>
    <Value>Exporting Information</Value>
    <ko_KR>내보내기 정보</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3691911Z"
    ModifiedDateTime="2017-10-31T06:53:14.3691911Z">
    <Type>Label</Type>
    <Name>ExportingType</Name>
    <Value>_Type</Value>
    <ko_KR>타입(T)</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3691911Z"
    ModifiedDateTime="2017-10-31T06:53:14.3691911Z">
    <Type>Label</Type>
    <Name>Comment</Name>
    <Value>Comment</Value>
    <ko_KR>설명</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3701924Z"
    ModifiedDateTime="2017-10-31T06:53:14.3701924Z">
    <Type>Label</Type>
    <Name>ImportingImformation</Name>
    <Value>Importing Information</Value>
    <ko_KR>가져오기 정보</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3701924Z"
    ModifiedDateTime="2017-10-31T06:53:14.3701924Z">
    <Type>Label</Type>
    <Name>ImportingType</Name>
    <Value>_Type</Value>
    <ko_KR>타입(T)</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3701924Z"
    ModifiedDateTime="2017-10-31T06:53:14.3701924Z">
    <Type>Button</Type>
    <Name>Export</Name>
    <Value>_Export</Value>
    <ko_KR>내보내기(_E)</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3701924Z"
    ModifiedDateTime="2017-10-31T06:53:14.3701924Z">
    <Type>Button</Type>
    <Name>Cancel</Name>
    <Value>_Cancel</Value>
    <ko_KR>취소(_C)</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3701924Z"
    ModifiedDateTime="2017-10-31T06:53:14.3701924Z">
    <Type>Button</Type>
    <Name>Import</Name>
    <Value>_Import</Value>
    <ko_KR>가져오기(_I)</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3701924Z"
    ModifiedDateTime="2017-10-31T06:53:14.3701924Z">
    <Type>Comment</Type>
    <Name>CommentForImporting</Name>
    <Value>Enter a comment for the import.</Value>
    <ko_KR>가져오기에 대한 설명을 입력하세요.</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3701924Z"
    ModifiedDateTime="2017-10-31T06:53:14.3701924Z">
    <Type>MenuItem</Type>
    <Name>Export</Name>
    <Value>_Export</Value>
    <ko_KR>내보내기(_E)</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3701924Z"
    ModifiedDateTime="2017-10-31T06:53:14.3701924Z">
    <Type>MenuItem</Type>
    <Name>Import</Name>
    <Value>_Import</Value>
    <ko_KR>가져오기(_I)</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3701924Z"
    ModifiedDateTime="2017-10-31T06:53:14.3701924Z">
    <Type>Label</Type>
    <Name>Path</Name>
    <Value>_Path</Value>
    <ko_KR>경로(_P)</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.3701924Z"
    ModifiedDateTime="2017-10-31T06:53:14.3701924Z">
    <Type>Label</Type>
    <Name>ExportByFolder</Name>
    <Value>Export by folder</Value>
    <ko_KR>폴더별로 나눠서 출력하기</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.371193Z"
    ModifiedDateTime="2017-10-31T06:53:14.371193Z">
    <Type>Label</Type>
    <Name>OmitAttribute</Name>
    <Value>Omit Tags and Enabled</Value>
    <ko_KR>태그 및 사용 여부 제외</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.371193Z"
    ModifiedDateTime="2017-10-31T06:53:14.371193Z">
    <Type>Label</Type>
    <Name>OmitSignatureDate</Name>
    <Value>Omit Creation and Modification Info</Value>
    <ko_KR>생성 및 변경 정보 제외</ko_KR>
  </StringTable>
  <StringTable
    CreatedDateTime="2017-10-31T06:53:14.371193Z"
    ModifiedDateTime="2017-10-31T06:53:14.371193Z">
    <Type>Label</Type>
    <Name>SelectAll</Name>
    <Value>Select _All</Value>
    <ko_KR>전체선택(_A)</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2017-11-28T07:43:30.1483186Z"
    Modifier="s2quake"
    ModifiedDateTime="2017-11-28T07:43:47.0899484Z">
    <Type>Label</Type>
    <Name>ExportOneTableToOneFile</Name>
    <Value>Export One Table To One File</Value>
    <ko_KR>테이블 하나당 파일 하나로 출력하기</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-12-07T05:20:17.8427343Z"
    Modifier="admin"
    ModifiedDateTime="2017-12-07T05:20:17.8427343Z">
    <Type>Label</Type>
    <Name>OutputDateFormat</Name>
    <Value>Date Format</Value>
    <ko_KR>날짜 포맷</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-12-07T05:31:53.978357Z"
    Modifier="admin"
    ModifiedDateTime="2017-12-07T05:31:53.978357Z">
    <Type>Label</Type>
    <Name>IncludeDate</Name>
    <Value>Include date in file name</Value>
    <ko_KR>출력파일에 날짜 포함시키기</ko_KR>
  </StringTable>
</Content>

=== s2quake/CremaRepository/databases/8fe111c0-b9a3-4da1-86af-2ae07cea6a53/tables/common/CommonServiceModel.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="4.0"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/common/CommonServiceModel ../Templates/StringTable.xsd"
  StringTable.Creator="admin"
  StringTable.CreatedDateTime="2017-10-23T07:16:01.2646706Z"
  StringTable.Modifier="s2quake"
  StringTable.ModifiedDateTime="2018-05-11T02:22:21.3996863Z"
  StringTable.Count="27"
  StringTable.ID="c0cab95d-e8db-454e-bfdd-db225b55d79e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable">
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6240804Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6240804Z">
    <Type>Exception</Type>
    <Name>CannotRename</Name>
    <Value>Could not rename to same name.</Value>
    <ko_KR>같은 이름으로 변경할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6240804Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-01-23T01:02:56.4738202Z">
    <Type>Exception</Type>
    <Name>CategoryNotFound_Format</Name>
    <Value>Could not find category path '{0}'.</Value>
    <ko_KR>"{0}" 경로를 찾을 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6240804Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-01-23T01:05:56.9489379Z">
    <Type>Exception</Type>
    <Name>DataBaseNotFound_Format</Name>
    <Value>Could not find database '{0}'.</Value>
    <ko_KR>"{0}" 데이터 베이스를 찾을 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6240804Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6240804Z">
    <Type>Exception</Type>
    <Name>DomainNotFound_Format</Name>
    <Value>Could not find domain ID "{0}".</Value>
    <ko_KR>"{0}" 도메인 아이디를 찾을 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6240804Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-01-23T01:12:31.1832307Z">
    <Type>Exception</Type>
    <Name>ItemNotFound_Format</Name>
    <Value>Could not find item '{0}'.</Value>
    <ko_KR>"{0}" 아이템 경로를 찾을 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6240804Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6240804Z">
    <Type>Exception</Type>
    <Name>TableNotFound_Format</Name>
    <Value>Could not find table "{0}".</Value>
    <ko_KR>"{0}" 테이블을 찾을 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6240804Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6240804Z">
    <Type>Exception</Type>
    <Name>TypeNotFound_Format</Name>
    <Value>Could not find type "{0}".</Value>
    <ko_KR>"{0}" 타입을 찾을 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6240804Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6240804Z">
    <Type>Exception</Type>
    <Name>UserNotFound_Format</Name>
    <Value>Could not find UserID "{0}".</Value>
    <ko_KR>"{0}" 사용자 아이디를 찾을 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6240804Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6240804Z">
    <Type>Exception</Type>
    <Name>AlreadyPublic</Name>
    <Value>It is already set to public.</Value>
    <ko_KR>이미 공개 사용으로 설정되어 있습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>AlreadyPrivate</Name>
    <Value>It is already set to private.</Value>
    <ko_KR>이미 개인 사용으로 설정되어 있습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>InvalidIDorPath</Name>
    <Value>Invalid ID or invalid path.</Value>
    <ko_KR>잘못된 아이디이거나 잘못된 경로입니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>CannotAddToPublic</Name>
    <Value>Unable to add user because it is set to public.</Value>
    <ko_KR>공개 사용으로 설정되어 있기 때문에 사용자를 추가할 수 없습니다..</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>CannotRemoveToPublic</Name>
    <Value>Unable to remove user because it is set to public.</Value>
    <ko_KR>공개 사용으로 설정되어 있기 때문에 사용자를 삭제할 수 없습니다..</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>AlreadyLocked</Name>
    <Value>It's already locked.</Value>
    <ko_KR>이미 잠겨 있습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>NotLocked</Name>
    <Value>It's not locked.</Value>
    <ko_KR>잠겨 있지 않습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>CannotMoveToSameFolder</Name>
    <Value>Cannot to move to the same folder.</Value>
    <ko_KR>같은 폴더로 이동할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>InheritedChildCannotRename</Name>
    <Value>Inherited child table cannot rename.</Value>
    <ko_KR>상속된 자식 테이블은 이름을 변경할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>InheritedChildCannotMove</Name>
    <Value>Inherited child table cannot move.</Value>
    <ko_KR>상속된 자식 테이블은 이동할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>InheritedChildCannotDelete</Name>
    <Value>Inherited child table cannot delete.</Value>
    <ko_KR>상속된 자식 테이블은 삭제할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>CannotSetTemplateToInherited</Name>
    <Value>Cannot to set template to inherited table.</Value>
    <ko_KR>상속된 테이블에 템플릿을 지정할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>CannotSetTemplateItself</Name>
    <Value>Cannot to set itself as template.</Value>
    <ko_KR>자기 자신을 템플릿으로 지정할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.6250814Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.6250814Z">
    <Type>Exception</Type>
    <Name>RootFolderCannotRename</Name>
    <Value>Root folder cannot rename.</Value>
    <ko_KR>최상위 폴더는 이름을 변경할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.626082Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.626082Z">
    <Type>Exception</Type>
    <Name>RootFolderCannotMove</Name>
    <Value>Root folder cannot move</Value>
    <ko_KR>최상위 폴더는 이동할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.626082Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.626082Z">
    <Type>Exception</Type>
    <Name>HaveNotPermission</Name>
    <Value>You do not have permission to perform</Value>
    <ko_KR>작업 수행 권한을 가지고 있지 않습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.626082Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.626082Z">
    <Type>Exception</Type>
    <Name>InheritedPrivateItemCannotAdd</Name>
    <Value>Inherited private item cannot add user</Value>
    <ko_KR>개인 사용 설정이 상속된 객체이기 때문에 사용자를 추가할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="admin"
    CreatedDateTime="2017-11-09T02:00:43.626082Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-09T02:00:43.626082Z">
    <Type>Exception</Type>
    <Name>InheritedPrivateItemCannotRemove</Name>
    <Value>Inherited private item cannot remove user</Value>
    <ko_KR>개인 사용 설정이 상속된 객체이기 때문에 사용자를 삭제할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-05-11T02:22:21.3996863Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-05-11T02:22:21.3996863Z">
    <Type>Exception</Type>
    <Name>AuthenticationDoesNotSigned</Name>
    <Value>authentication does not signed.</Value>
    <ko_KR>서명되지 않은 인증입니다.</ko_KR>
  </StringTable>
</Content>

=== s2quake/CremaRepository/databases/8fe111c0-b9a3-4da1-86af-2ae07cea6a53/tables/client/ClientServices.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="4.0"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/client/ClientServices ../Templates/StringTable.xsd"
  StringTable.Creator="admin"
  StringTable.CreatedDateTime="2017-10-23T07:16:01.2646706Z"
  StringTable.Modifier="s2quake"
  StringTable.ModifiedDateTime="2018-03-27T02:40:05.917075Z"
  StringTable.Count="18"
  StringTable.ID="22a47b84-acb1-4006-b4ba-d3e85d577a0d" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/StringTable">
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:01:04.4153623Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:02:06.269471Z">
    <Type>Exception</Type>
    <Name>AlreadyConnected</Name>
    <Value>It's already connected.</Value>
    <ko_KR>이미 연결되어 있습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:02:43.1323357Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:03:13.9735899Z">
    <Type>Exception</Type>
    <Name>NotConnected</Name>
    <Value>It's not connected.</Value>
    <ko_KR>연결되어 있지 않습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:05:26.714223Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:36:41.4319158Z">
    <Type>Exception</Type>
    <Name>InvalidName_Format</Name>
    <Comment>name</Comment>
    <Value>'{0}' is not valid name.</Value>
    <ko_KR>'{0}'은(는) 유효하지 않은 이름입니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:12:12.3773356Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:16:59.9014406Z">
    <Type>Exception</Type>
    <Name>InvalidToken</Name>
    <Value>It is not valid token</Value>
    <ko_KR>유효한 토큰이 아닙니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:14:10.7191434Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:14:25.86677Z">
    <Type>Exception</Type>
    <Name>Expired</Name>
    <Value>It has been expired.</Value>
    <ko_KR>만료되었습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:15:47.7045138Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:15:59.5449346Z">
    <Type>Exception</Type>
    <Name>Commissioned</Name>
    <Value>It's already been commissioned.</Value>
    <ko_KR>이미 위임중입니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:16:31.3533904Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:16:55.9858337Z">
    <Type>Exception</Type>
    <Name>InvalidID</Name>
    <Value>It is not valid ID</Value>
    <ko_KR>유효한 아이디가 아닙니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:19:11.0664709Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:19:41.3305241Z">
    <Type>Exception</Type>
    <Name>NotAllowedAsPublic</Name>
    <Value>This class is not allowed as public</Value>
    <ko_KR>이 클래스는 public으로 사용할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:20:47.5994405Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:21:08.0042763Z">
    <Type>Exception</Type>
    <Name>NotClosed</Name>
    <Value>It is not closed.</Value>
    <ko_KR>닫혀있지 않습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:21:36.6771267Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:21:54.2115575Z">
    <Type>Exception</Type>
    <Name>AlreadyDisposed</Name>
    <Value>It has been disposed.</Value>
    <ko_KR>이미 제거되었습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:23:04.3024806Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:23:15.4721002Z">
    <Type>Exception</Type>
    <Name>NotOpened</Name>
    <Value>It is not opened.</Value>
    <ko_KR>열려있지 않습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:24:05.7353885Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:24:20.3058141Z">
    <Type>Exception</Type>
    <Name>InvalidObject</Name>
    <Value>It is not valid object.</Value>
    <ko_KR>유효하지 않은 객체입니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:24:40.8822502Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:27:04.9173032Z">
    <Type>Exception</Type>
    <Name>NotInDataBase</Name>
    <Value>It cannot work operation, because you are not in database</Value>
    <ko_KR>데이터베이스에 참여하고 있지 않으므로 작업을 수행할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:28:07.5514132Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:28:22.8550401Z">
    <Type>Exception</Type>
    <Name>NotBeingEdited</Name>
    <Value>It is not being edited.</Value>
    <ko_KR>편집중이 아닙니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:32:18.3062537Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:32:18.3062537Z">
    <Type>Exception</Type>
    <Name>InvalidName</Name>
    <Value>It is not valid name.</Value>
    <ko_KR>유효지 않은 이름입니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:35:11.7629583Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:35:11.7629583Z">
    <Type>Exception</Type>
    <Name>CannotRename</Name>
    <Value>It cannot rename.</Value>
    <ko_KR>이름은 변경할 수 없습니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:36:36.3307069Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:37:14.2699735Z">
    <Type>Exception</Type>
    <Name>InvalidProperty_Format</Name>
    <Comment>propertyName</Comment>
    <Value>'{0}' is not valid property name.</Value>
    <ko_KR>'{0}'은(는) 유효하지 않은 속성 이름입니다.</ko_KR>
  </StringTable>
  <StringTable
    Creator="s2quake"
    CreatedDateTime="2018-03-27T02:39:13.8129835Z"
    Modifier="s2quake"
    ModifiedDateTime="2018-03-27T02:40:05.917075Z">
    <Type>Exception</Type>
    <Name>CannotEnter</Name>
    <Value>It cannot enter to database that is not loaded.</Value>
    <ko_KR>활성화되어 있지 않은 데이터베이스에는 참여할 수 없습니다.</ko_KR>
  </StringTable>
</Content>
